version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ebf
    ports:
      - "3308:3306"

  app:
    image: ebf-auth:latest
    ports:
      - "9000:9000"
    environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false"
    depends_on:
        - mysql
