server:
  port: 9000
  servlet:
    contextPath: /auth

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/ebf
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  ignored:
    - "*.bundle.*"
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      authorized-grant-types:
        - authorization_code
        - refresh_token
        - password
      scope: openid
      registered-redirect-uri:
        - http://localhost:8080
        - http://localhost:8080/login
      pre-established-redirect-uri: http://localhost:8080
      use-current-uri: false
